services:
  - type: web
    name: domainspos-api
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: singapore

    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        value: "8080"
      - key: DB_SSLMODE
        value: require
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
